[project]
name = "trellis"
version = "0.1.0"
description = "AI agent that converts vague goals into actionable sprints"
readme = "README.md"
requires-python = ">=3.12"

# core runtime deps
dependencies = [
  "openai-agents",
  "langgraph",
  "weaviate-client",
  "fastapi[all]",
  "pydantic",
  "python-dotenv",
  "ruff",
  "pytest",
  "typer[all]",
  "whisper-timestamped @ git+https://github.com/linto-ai/whisper-timestamped",
  "TTS"
]

[project.optional-dependencies]
dev = ["pre-commit", "mypy", "ipykernel"]

[tool.setuptools]
package-dir = {"" = "packages"}

[tool.setuptools.packages.find]
where = ["packages"]

[build-system]
requires = ["setuptools>=67", "wheel"]
build-backend = "setuptools.build_meta"
