name: Sync main to dev

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge main into dev
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin main
          git merge origin/main --no-edit
          git push origin dev
